# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port 8000
EXPOSE 8004

# Run the application using uvicorn
CMD ["uvicorn", "webapp2:app", "--host", "0.0.0.0", "--port", "8004"]